mnist:
  dataset_name: "mnist"
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  resize_to: [128, 128]

cifar10:
  dataset_name: "cifar10"
  num_epochs: 100
  batch_size: 128
  learning_rate: 0.001
  resize_to: [128, 128]